NAMES = ('JACK', 'JIMMY', 'JACKSON', 'JHON', 'JACKSON', 'JHON',  'JIMMY', 'JACKSON', 'JHON','JACK', 'JIMMY', 'JACK', 'JACKSON', 'JHON', 'JACKSON', 'JHON','JACK', 'JIMMY', 'JACK', 'JACKSON', 'JHON')
NAMES15 = NAMES[0:15]
print(NAMES15[0:3])
print(NAMES15[3:6])
print(NAMES15[6:9])
print(NAMES15[9:12])
print(NAMES15[12:15])